# Generated by Django 5.0.2 on 2024-09-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_snsid_user_user_manual_alter_user_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobby',
        ),
        migrations.AddField(
            model_name='user',
            name='hobbys',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
