# Generated by Django 5.0.2 on 2024-09-23 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_hobby_user_hobbys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skil',
        ),
    ]
