# Generated by Django 5.0.2 on 2024-09-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_skil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
