# Generated by Django 5.0.2 on 2024-09-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_post_user_delete_accesstoken_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skils',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
