# Generated by Django 5.0.2 on 2024-09-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_skils'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matched_user',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
