# Generated by Django 5.0.2 on 2024-09-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_matched_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='matched_user',
            new_name='matched_users',
        ),
    ]
