# Generated by Django 5.0.2 on 2024-09-23 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_matched_user_user_matched_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_match_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
