# Generated by Django 5.0.2 on 2025-01-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_chatroom_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='related_chat_rooms',
            field=models.ManyToManyField(blank=True, related_name='members', to='app.chatroom'),
        ),
    ]
